version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - PORT=${PORT}
    command: 'npm run start'
    ports:
      - 3000:3000
    volumes:
      - .:/app
